Optimizing dated partition
VaBezruchko/spark-clickhouse-connector pull request #5
Opened 2020-01-08 09:36 UTC by cnmac

1. The position of the for loop needs to be adjusted, otherwise concurrent tasks will be executed on one clickhouse shard.
2. The dated partition key is usually of type DateTime, add clickhouse function for formatting.

2020-01-19 19:14 UTC, VaBezruchko requested changes
there are a lot of changes with code style and i cannot find any changes for this section: "The position of the for loop needs to be adjusted, otherwise concurrent tasks will be executed on one clickhouse shard." 
Could you please split your 'pull request' into two parts? For example: first part 'code style' + 'The dated partition key <..>' and  second part 'The position of the for loop <...>'

2020-01-19 19:14 UTC, VaBezruchko commented on spark-clickhouse-connector/src/main/scala/io/clickhouse/spark/connector/ClickhouseRDD.scala
> +  def withoutDatedPartitioning(startDt: DateTime, endDt: DateTime, rangeType: RangeType, partitionKeyName: String): Self = {
Why you need this method? What is the difference between this method and the "withPeriod" method? Also very strange naming for this method.

2020-01-19 19:14 UTC, VaBezruchko commented on spark-clickhouse-connector/src/main/scala/io/clickhouse/spark/connector/partitioner/ClickhousePartition.scala
> +      s"toYYYYMMDD($pk) = '${dated.toString("yyyyMMdd")}'"
There's an error. Need to remove the single quotes because the result of toYYYYMMDD func is Int.

2020-03-03 03:29 UTC, cnmac commented
OK，Let's solve the problem of for loop first

2020-03-19 19:09 UTC, merged

2020-03-19 19:11 UTC, VaBezruchko commented
Thanks for your improvements.